const s = {
  container:    { minHeight: '100vh', width: '100%', backgroundColor: '#f1f5f9', padding: '30px', boxSizing: 'border-box', fontFamily: 'Inter, sans-serif' },
  header:       { maxWidth: '1400px', margin: '0 auto 25px', display: 'flex', justifyContent: 'space-between', alignItems: 'center' },
  title:        { margin: 0, fontSize: '26px', color: '#0f172a', fontWeight: '700' },
  subtitle:     { color: '#64748b', margin: '4px 0 0' },
  card:         { backgroundColor: '#fff', borderRadius: '12px', boxShadow: '0 4px 6px rgba(0,0,0,0.05)', padding: '25px', maxWidth: '1400px', margin: '0 auto' },
  input:        { padding: '10px 15px', borderRadius: '8px', border: '1px solid #cbd5e1', outline: 'none', fontSize: '14px' },
  th:           { padding: '15px', textAlign: 'left', color: '#64748b', fontSize: '12px', fontWeight: '700', textTransform: 'uppercase', backgroundColor: '#f8fafc', borderBottom: '2px solid #f1f5f9' },
  thCenter:     { padding: '15px', textAlign: 'center', color: '#64748b', fontSize: '12px', fontWeight: '700', textTransform: 'uppercase', backgroundColor: '#f8fafc', borderBottom: '2px solid #f1f5f9' },
  td:           { padding: '15px', borderBottom: '1px solid #f1f5f9', fontSize: '14px', verticalAlign: 'middle' },
  tdCenter:     { padding: '15px', borderBottom: '1px solid #f1f5f9', fontSize: '14px', verticalAlign: 'middle', textAlign: 'center' },
  btnBlue:      { backgroundColor: '#2563eb', color: '#fff', border: 'none', padding: '10px 20px', borderRadius: '8px', fontWeight: '600', cursor: 'pointer' },
  btnGreen:     { backgroundColor: '#16a34a', color: '#fff', border: 'none', padding: '10px 20px', borderRadius: '8px', fontWeight: '600', cursor: 'pointer' },
  btnAction:    { padding: '6px 12px', borderRadius: '6px', fontSize: '12px', fontWeight: '600', cursor: 'pointer', border: '1px solid #e2e8f0', backgroundColor: '#fff', transition: '0.2s', display: 'inline-flex', alignItems: 'center', gap: '5px' },
  btnDelete:    { color: '#ef4444', borderColor: '#fecaca' },
  btnToggle:    { fontSize: '11px', padding: '4px 8px' },
  badge:        { padding: '4px 10px', borderRadius: '12px', fontSize: '12px', fontWeight: '600' },
  badgeActif:   { backgroundColor: '#f0fdf4', color: '#15803d' },
  badgeInactif: { backgroundColor: '#f9fafb', color: '#6b7280' },
  headerBtns:   { display: 'flex', gap: '10px' },
  filtreBtns:   { display: 'flex', gap: '10px', marginBottom: '25px' },
  btnRow:       { display: 'flex', gap: '8px', justifyContent: 'center' },
  tableWrap:    { overflowX: 'auto' },
  table:        { width: '100%', borderCollapse: 'collapse' },
  modalOverlay: { position: 'fixed', inset: 0, backgroundColor: 'rgba(15, 23, 42, 0.5)', zIndex: 1000, display: 'flex', alignItems: 'center', justifyContent: 'center', backdropFilter: 'blur(4px)' },
  modalContent: { backgroundColor: '#fff', borderRadius: '12px', width: '450px', boxShadow: '0 20px 25px rgba(0,0,0,0.15)', overflow: 'hidden' },
  modalHeader:  { padding: '20px', backgroundColor: '#f8fafc', borderBottom: '1px solid #e2e8f0', display: 'flex', justifyContent: 'space-between', alignItems: 'center' },
  modalForm:    { padding: '24px' },
  modalFooter:  { display: 'flex', justifyContent: 'flex-end', gap: '10px', paddingTop: '15px', borderTop: '1px solid #f1f5f9' },
  alertBase:    { padding: '12px 20px', borderRadius: '8px', border: '1px solid', maxWidth: '1400px', margin: '0 auto 20px' },
  alertSuccess: { backgroundColor: '#f0fdf4', color: '#16a34a', borderColor: '#bbf7d0' },
  alertDanger:  { backgroundColor: '#fef2f2', color: '#dc2626', borderColor: '#fecaca' },
};

export default s;